security:
  oauth2:
    client:
      client-id: b219aad39642fc2f8ecd
      client-secret: e1e716739e6a9f8103474d029c1d9529d037aa9f
      access-token-uri: https://github.com/login/oauth/access_token
      user-authorization-uri: https://github.com/login/oauth/authorize
      accessTokenUri: https://github.com/login/oauth/access_token
      userAuthorizationUri: https://github.com/login/oauth/authorize
      scope: read,write
      auto-approve-scopes: '.*'
      use-current-uri: false
  
  github:
    client:
      client-id: b219aad39642fc2f8ecd
      client-secret: e1e716739e6a9f8103474d029c1d9529d037aa9f
      access-token-uri: https://github.com/login/oauth/access_token
      user-authorization-uri: https://github.com/login/oauth/authorize
      client-authentication-scheme: form
      accessTokenUri: https://github.com/login/oauth/access_token
      userAuthorizationUri: https://github.com/login/oauth/authorize
      clientId: b219aad39642fc2f8ecd
      clientSecret: e1e716739e6a9f8103474d029c1d9529d037aa9f
    resource:
      user-info-uri: https://api.github.com/user
      userInfoUri: https://api.github.com/user
github:
  client:
    clientId: b219aad39642fc2f8ecd
    clientSecret: e1e716739e6a9f8103474d029c1d9529d037aa9f
    accessTokenUri: https://github.com/login/oauth/access_token
    userAuthorizationUri: https://github.com/login/oauth/authorize
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://api.github.com/user
    